### ISSUE TITLE
简单代码分析的问题

### ISSUE THREAD

**Issue by weichao-csu** [wh1t3p1g/tabby#10]
师傅您好，感谢您前面看了我的那个0除的问题，后面我也拜读了您的文章《如何高效的挖掘Java反序列化利用链？》和使用说明，但是还是有一些小小的疑惑，就是针对于分析这种小量的代码还有使用上的一些问题，希望您能不吝赐教
`/**
 * @author 
 * Belong to TestDemo.iml
 * @date 2021-05-02-12:27
 * @description
 */

import java.io.IOException;
import java.io.Serializable;

public class user implements Serializable {

    private String name;

    public String getName() {

        return name;

    }

    public void setName(String name) {

        this.name = name;

    }
    private void readObject(java.io.ObjectInputStream in) throws ClassNotFoundException, IOException {

        try {
            in.defaultReadObject();
        } catch (IOException e) {
            e.printStackTrace();
        }

        Runtime.getRuntime().exec("calc.exe");

    }

}`

另外一个
`

/**
 * @author 乐伟超
 * Belong to TestDemo.iml
 * @date 2021-05-02-12:28
 * @description
 */

import java.io.FileInputStream;

import java.io.FileNotFoundException;

import java.io.FileOutputStream;

import java.io.IOException;

import java.io.ObjectInputStream;

import java.io.ObjectOutputStream;

public class test1 {

    public static void main(String[] args) {

        try {

            FileOutputStream out = new FileOutputStream("d:/1.bin");

            ObjectOutputStream obj_out = new ObjectOutputStream(out);

            user u = new user();

            u.setName("test");

            obj_out.writeObject(u);

//利用readobject方法还原user对象

            FileInputStream in = new FileInputStream("d:/1.bin");

            ObjectInputStream ins = new ObjectInputStream(in);
            //反序列化操作
            user u1 = (user) ins.readObject();

            System.err.println(u1.getName());

        } catch (FileNotFoundException e) {

// TODO Auto-generated catch block

            e.printStackTrace();

        } catch (IOException e) {

            e.printStackTrace();

        } catch (ClassNotFoundException e) {

            e.printStackTrace();

        }

    }

}

`
就是上面两个简单的类，构建了Demo.jar文件
用tabby分析以后，导入到neo4j中很明显main中就有好多CALL没有显示出来
我用的是 java -Xmx6g -jar tabby-1.1.0.RELEASE.jar Demo.jar  命令，
不知是不是没有分析jre或者是jdk环境造成的
![pro](https://user-images.githubusercontent.com/82953161/119657998-38db5180-be5f-11eb-8adf-310b14c01a4d.png)

我还有一个使用上的问题，就是在我分析某个组件或者是插件的时候，如果不分析JDK或者jre的话是不是调用的jdk内部的类之间的调用关系就不会生成，
就比如外部的某个组件用到了Map类，调用了putAll方法，进而putAll又调用JDK内部的put再到compareTo()方法，如果只分析组件不分析jdk或者是jre，是不是就只会生成到外部组件调用到putAll就停止了，没有了后面的调用关系

**Comment by wh1t3p1g** [comment]
关于很多调用边没有出来是因为当前会去除掉不可控的函数调用。譬如，exec参数是固定string，是不可控的，所以不会出现在图中

关于jdk内部类的分析，需要在分析时加上--isJDKProcess

**Comment by weichao-csu** [comment]
懂了，tabby的目标是寻找可控参数的利用途径，谢谢师傅
