### ISSUE TITLE
CALL边的POLLUTED_POSITION

### ISSUE THREAD

**Issue by weichao-csu** [wh1t3p1g/tabby#11]
师傅您好，我现在正在想办法去寻找自动化挖掘JAVA反序列化的方法，您能不能就 “参数为CALL边的POLLUTED_POSITION”这个属性给出具体的JAVA代码和参数说明，直接看您的例子没有代码，我很难理解这里面的数组的值在实际调用中都代表着一些什么
不胜感激

**Comment by wh1t3p1g** [comment]
老哥 可以加我wx
