### ISSUE TITLE
简单代码分析问题

### ISSUE THREAD

**Issue by qiqingshiwo** [wh1t3p1g/tabby#12]
师傅您好,最近在使用tabby分析demo的时候,不知道是不是操作原因造成的了一些问题,想问下师傅
这是我的代码:
![image](https://user-images.githubusercontent.com/33613050/123053784-d615af80-d436-11eb-859a-a9ab90aff821.png)
![image](https://user-images.githubusercontent.com/33613050/123053833-e29a0800-d436-11eb-8ea5-06cb8bd159ff.png)
然后我用这个命令去分析
![image](https://user-images.githubusercontent.com/33613050/123054070-15dc9700-d437-11eb-88e6-f5756484f93e.png)
然后在neo4j里面的关系图上只有service,没有serviceImpl,从关系图上看没走到readObject
![image](https://user-images.githubusercontent.com/33613050/123054554-8d122b00-d437-11eb-9f9f-623481fc5884.png)
想问下师傅,这种情况有办法解决吗?

**Comment by qiqingshiwo** [comment]
![image](https://user-images.githubusercontent.com/33613050/123055587-a667a700-d438-11eb-9b19-dc7cb1308cd8.png)

**Comment by wh1t3p1g** [comment]
你好，可以把jar发我邮箱，或者其他什么地方，我空下来了看看什么原因

**Comment by wh1t3p1g** [comment]
另外，可以把查询语句附上，我看图里并没有ALIAS边。
对于这种需要跳转到具体实现上时，需要加上ALIAS边的检索。

**Comment by qiqingshiwo** [comment]
师傅您好,邮件已发送,抱歉😂,好像发到wh1t3p1g@gmail.com这个邮箱去了

**Comment by LuckyC4t** [comment]
正常情况下，tabby在分析UserServiceImpl这个类中的方法CheckUser时，会去寻找接口IUserService中的同名方法，两者之间建立alias边。在分析IUserService中的CheckUser没有收获后可以沿着alias边继续分析UserServiceImpl中的CheckUser。个人做了个实验，
目录结构：
![image](https://user-images.githubusercontent.com/40694340/124311050-b2253d00-db9f-11eb-8826-680488b20cff.png)
Entry.java
```java
import java.io.ByteArrayInputStream;
import java.util.Base64;

public class Entry {
    private IUserService userService;

    public void read(String read) {
        ByteArrayInputStream bis = new ByteArrayInputStream(Base64.getDecoder().decode(read));
        this.userService.CheckUser(bis);
    }

    public static void main(String[] args) {

    }
}
```
IUserService.java
```java
import java.io.InputStream;

public interface IUserService {
    public void CheckUser(InputStream out);
}
```
UserServiceImpl.java
```java
import java.io.InputStream;
import java.io.ObjectInputStream;

public class UserServiceImpl implements IUserService {
    @Override
    public void CheckUser(InputStream out) {
        try {
            ObjectInputStream ois = new ObjectInputStream(out);
            ois.readObject();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
}
```
打包成jar后用tabby分析，在neo4j中确实可以通过alias边追踪到readObject
![image](https://user-images.githubusercontent.com/40694340/124311251-07f9e500-dba0-11eb-8b0c-197389d240f4.png)

**Comment by qiqingshiwo** [comment]
两位师傅好,很抱歉这么晚回复你们,我这段时间忙别的去了,一时忘记这个issue了,wh1t3p1g师傅的邮件已收到,非常感谢师傅的解答,我已发现为啥不能找到的原因
![image](https://user-images.githubusercontent.com/33613050/125778492-0abcbb5b-aab3-4fbc-b1c2-526fd1a4d6fe.png)
我在test01下面还有一层目录,这个被当成了包的一部分,导致neo4j里面没找到这个CheckUser,这个个人操作失误希望能帮到后面的同学
