### ISSUE TITLE
未开启过程间分析

### ISSUE THREAD

**Issue by r00t4dm** [wh1t3p1g/tabby#13]
这个commit关闭了过程间分析

https://github.com/wh1t3p1g/tabby/commit/b17dfc44f0cb87548ff786c8433a43b392dfa46c

导致如下错误
java.lang.RuntimeException: This operation requires resolving level BODIES but java.lang.AbstractStringBuilder is at resolving level SIGNATURES
If you are extending Soot, try to add the following call before calling soot.Main.main(..):
Scene.v().addBasicClass(java.lang.AbstractStringBuilder,BODIES);
Otherwise, try whole-program mode (-w).
	at soot.SootClass.checkLevelIgnoreResolving(SootClass.java:198)
	at soot.SootClass.checkLevel(SootClass.java:180)
	at soot.SootMethod.retrieveActiveBody(SootMethod.java:391)

**Comment by wh1t3p1g** [comment]
感谢提交，已修复XD #
