### ISSUE TITLE
注解类/方法支持

### ISSUE THREAD

**Issue by RicterZ** [wh1t3p1g/tabby#15]
使用tabby的时候发现调用链上缺少有注解的方法，还未具体写测试用例深入测试。有没有增加注解方法的支持的计划？

<del>改动哪部分代码比较好我可以自己看看</del>

**Comment by wh1t3p1g** [comment]
师傅，有没有注解场景的示例？

**Comment by RicterZ** [comment]
破案了，是不处理参数不可控的函数调用。
不过实际测试审计过程中，对于一些检测可能不可控的参数可能通过其他路径可控，比如数据库查询的内容等。
在日常审计中使用tabby还是要做一些代码修改，否则可能会遗漏一些东西。

**Comment by wh1t3p1g** [comment]
> 破案了，是不处理参数不可控的函数调用。
> 不过实际测试审计过程中，对于一些检测可能不可控的参数可能通过其他路径可控，比如数据库查询的内容等。
> 在日常审计中使用tabby还是要做一些代码修改，否则可能会遗漏一些东西。

是的，常规漏洞目前正在磨合期，2333
