### ISSUE TITLE
windows下file://改file:///

### ISSUE THREAD

**Issue by HYWZ36** [wh1t3p1g/tabby#16]
在Windows下运行程序进入到【Save methods to Neo4j.】阶段时，程序会错误中断，此时没有有效的语义提示信息，卡住了。
解决办法是修改源代码中file://为file:///，并在此基础上运行程序根据提示信息自适应修改目标csv所在路径就行啦。

**Comment by HYWZ36** [comment]
师傅，是这里文件下面file协议硬编码是file://
![image](https://user-images.githubusercontent.com/27775281/139804881-b2bb893b-f629-45a5-ad1e-3aad92e25503.png)

**Comment by wh1t3p1g** [comment]
这个会先过前面提到的函数的
或许可以测试一下是不是这个win的判断有问题

**Comment by HYWZ36** [comment]
哦哦，尴尬，我使用的版本老了一些没有这个过滤，打扰啦
