### ISSUE TITLE
新版本配置文件处有一个小bug，导致isJDKOnly无法正常运行

### ISSUE THREAD

**Issue by Z3ratu1** [wh1t3p1g/tabby#25]
配置文件中有一行设置了default的target
`tabby.build.target                    = cases/commons-collections-3.1.jar`
而主程序有一个如下判断
```java
        // 支持绝对路径 issue 7
        if(target != null && !FileUtils.fileExists(target)){
            target = String.join(File.separator, System.getProperty("user.dir"), target);
            log.info("target: " + target);
            if(!FileUtils.fileExists(target)){
                throw new IllegalArgumentException("target not exists!");
            }
        }
```
这使得target永远不是null，isJDKOnly时也不会忽略该选项，导致运行报错（以及最新released的源码好像也和这批源码有出入。。。）

**Comment by wh1t3p1g** [comment]
感谢提交，已修复 https://github.com/wh1t3p1g/tabby/commit/08b619b0bab7dcfb67ddf78612936b2c74838cae
最新的还未发release

**Comment by Z3ratu1** [comment]
还有一些相关的小问题，比如isSaveOnly算是被移除了吗？只看到一个tabby.load.enable，似乎还是会再走一遍解析流程

**Comment by wh1t3p1g** [comment]
是的，现在开启导入neo4j 就配置tabby.load.enable

**Comment by Z3ratu1** [comment]
okk，麻烦师傅了
