### ISSUE TITLE
添加注解支持

### ISSUE THREAD

**Issue by cwkiller** [wh1t3p1g/tabby#35]
审计过程中多次遇到判断方法或者所在类是否存在某个注解来进行鉴权，需要注解支持。

**Comment by wh1t3p1g** [comment]
1. 因为要尽可能压缩数据量，暂时不存所有的注解
2. 可以添加一个boolean标签，可以提供一些常见的鉴权注解，我后续加上该标签

**Comment by cwkiller** [comment]
常见的鉴权注解，就是shiro和springsecurity的权限注解，我这边因为有很多别的需求所以自己添加了注解和注解值支持。
