### ISSUE TITLE
分析速度慢，不确定是不是我的姿势有问题

### ISSUE THREAD

**Issue by einhhhh** [wh1t3p1g/tabby#36]
师傅好，使用tabby分析几个包，一共6000多个类，但是分析了2个多小时都没完成。请问有加快分析速度的方式吗

**Comment by wh1t3p1g** [comment]
是卡在分析阶段还是导入阶段

**Comment by einhhhh** [comment]
> 

是在分析阶段哈，ClassInfoScanner这个阶段

**Comment by einhhhh** [comment]
> 是卡在分析阶段还是导入阶段

实测发现12h才能分析完2300个类，电脑CPU配置是12代i5，我看师傅是用mac pro做分析不确定是否自己的硬件落了后腿

**Comment by wh1t3p1g** [comment]
是2300个jar包么

**Comment by einhhhh** [comment]
> 是2300个jar包么

不是噢，就8个jar包里面有6000多个类。但是分析时间太长了

**Comment by einhhhh** [comment]
aspectjweaver-1.9.8.jar ognl-3.3.4.jar aspectjrt-1.9.8.jar aspectjtools-1.9.8.jar 这是其中四个

**Comment by einhhhh** [comment]
# build code property graph tabby.build.enable                    = true # jdk settings tabby.build.isJDKProcess              = true tabby.build.withAllJDK                = false  tabby.build.excludeJDK                = false tabby.build.isJDKOnly                 = false  # dealing fatjar tabby.build.checkFatJar               = true  # default pointed-to analysis tabby.build.isFullCallGraphCreate     = true  # targets to analyse #tabby.build.target                    = path/to/target tabby.build.target                    = cases/ # tabby.build.libraries                 = path/to/lib  # load to neo4j tabby.load.enable                     = true  # debug tabby.debug.details                   = true tabby.debug.inner.details             = true

**Comment by einhhhh** [comment]
以下是配置信息
```
# build code property graph tabby.build.enable                    = true # jdk settings tabby.build.isJDKProcess              = true tabby.build.withAllJDK                = false  tabby.build.excludeJDK                = false tabby.build.isJDKOnly                 = false  # dealing fatjar tabby.build.checkFatJar               = true  # default pointed-to analysis tabby.build.isFullCallGraphCreate     = true  # targets to analyse #tabby.build.target                    = path/to/target tabby.build.target                    = cases/ # tabby.build.libraries                 = path/to/lib  # load to neo4j tabby.load.enable                     = true  # debug tabby.debug.details                   = true tabby.debug.inner.details             = true 
```

**Comment by wh1t3p1g** [comment]
配置上没问题，分析的数量也不多，也没有用污点分析，感觉可能跟电脑有关系了

**Comment by einhhhh** [comment]
> 配置上没问题，分析的数量也不多，也没有用污点分析，感觉可能跟电脑有关系了

请问是普通的PC不具备使用Tabby快速分析的条件吗，但是我看了下CPU的资源占用，并不是太高，还是说需要配置些东西呢；此外，我也使用了苹果m1 pro的mac进行分析，速度和在PC上差不多....

**Comment by wh1t3p1g** [comment]
> > 配置上没问题，分析的数量也不多，也没有用污点分析，感觉可能跟电脑有关系了
> 
> 请问是普通的PC不具备使用Tabby快速分析的条件吗，但是我看了下CPU的资源占用，并不是太高，还是说需要配置些东西呢；此外，我也使用了苹果m1 pro的mac进行分析，速度和在PC上差不多....

可以用的哈，我现在也是 m1 pro 在跑的，jdk sdk 3w+ 类大概6 7分钟的样子，你加一下我微信吧 我id

**Comment by wh1t3p1g** [comment]
解决方案：删除cache目录下的db文件
