### ISSUE TITLE
必须分析JDK吗

### ISSUE THREAD

**Issue by FizzFish** [wh1t3p1g/tabby#38]
你好，tabby静态分析CFG必须包含JDK吗，但是这样子生成的neo4j是不是太大了。
我写了简单的测试例子，node节点达到了21万^^，而且时间非常长。
_Total nodes: 213563, relations: 715798_
而且，无论怎么修改setting中的jdk选项，还是这个结果，请问这几个属性含义在哪里有解释吗
```
tabby.build.isJDKProcess              = false
tabby.build.withAllJDK                = false
tabby.build.excludeJDK                = true
tabby.build.isJDKOnly                 = false
```

**Comment by wh1t3p1g** [comment]
全部改成 false 就不会处理全量的 jdk
相关介绍见 [wiki](https://github.com/wh1t3p1g/tabby/wiki/Tabby%E9%A3%9F%E7%94%A8%E6%8C%87%E5%8C%97#%E7%89%B9%E6%AE%8A%E5%AE%9E%E9%99%85%E5%9C%BA%E6%99%AF%E4%B8%BE%E4%BE%8B)

**Comment by FizzFish** [comment]
xiexie

> 全部改成 false 就不会处理全量的 jdk 相关介绍见 [wiki](https://github.com/wh1t3p1g/tabby/wiki/Tabby%E9%A3%9F%E7%94%A8%E6%8C%87%E5%8C%97#%E7%89%B9%E6%AE%8A%E5%AE%9E%E9%99%85%E5%9C%BA%E6%99%AF%E4%B8%BE%E4%BE%8B)

谢谢。
但我全改成false，节点数也没有减少，要满CPU处理很久，不知道为什么。
```
# build code property graph
tabby.build.enable                    = false
# jdk settings
tabby.build.isJDKProcess              = false
tabby.build.withAllJDK                = false
tabby.build.excludeJDK                = false
tabby.build.isJDKOnly                 = false

# dealing fatjar
tabby.build.checkFatJar               = true

# default pointed-to analysis
tabby.build.isFullCallGraphCreate     = true

# targets to analyse
#tabby.build.target                    = path/to/target
tabby.build.target                    = path/target/User.jar
tabby.build.libraries                 = path/to/lib

# load to neo4j
tabby.load.enable                     = true

# debug
tabby.debug.details                   = false
tabby.debug.inner.details             = false
```

**Comment by wh1t3p1g** [comment]
你的配置是导入到neo4j，没有重新生成图

**Comment by FizzFish** [comment]
感谢师傅的回复。
上面的配置可能是我胡乱试的一个状态，大部分情况下我是打开tabby.build.enable的。
我又做了一个测试，现在我的配置如下，user.jar内容很简单，但是还是会生成巨大的属性图。
```
# build code property graph
tabby.build.enable                    = true
# jdk settings
tabby.build.isJDKProcess              = false
tabby.build.withAllJDK                = false
tabby.build.excludeJDK                = false
tabby.build.isJDKOnly                 = false

# dealing fatjar
tabby.build.checkFatJar               = true

# default pointed-to analysis
tabby.build.isFullCallGraphCreate     = true

# targets to analyse
#tabby.build.target                    = path/to/target
tabby.build.target                    = path/tar/user.jar
tabby.build.libraries                 = path/lib

# load to neo4j
tabby.load.enable                     = true

# debug
tabby.debug.details                   = false
tabby.debug.inner.details             = false```

运行结果还是显示加载了3个jre，生成213k个节点，716k条边。。
怎样才能只生成user.jar中的属性图呢，有点困惑了
```
2022-11-02 18:04:27.273  INFO 18504 --- [           main] tabby.core.container.RulesContainer      : load 54 rules success!
2022-11-02 18:04:27.390  INFO 18504 --- [           main] org.neo4j.driver.Driver                  : Direct driver instance 367589810 created for server address 127.0.0.1:7687
2022-11-02 18:04:28.014  INFO 18504 --- [           main] o.s.s.concurrent.ThreadPoolTaskExecutor  : Initializing ExecutorService
2022-11-02 18:04:28.015  INFO 18504 --- [           main] o.s.s.concurrent.ThreadPoolTaskExecutor  : Initializing ExecutorService 'tabby-collector'
2022-11-02 18:04:28.172  INFO 18504 --- [           main] tabby.App                                : Started App in 3.356 seconds (JVM running for 3.697)
2022-11-02 18:04:28.432  INFO 18504 --- [           main] tabby.core.Analyser                      : Load 3 jre jars.
2022-11-02 18:04:28.432  INFO 18504 --- [           main] tabby.core.Analyser                      : Get 3 JDK dependencies
2022-11-02 18:04:28.477  INFO 18504 --- [           main] tabby.core.Analyser                      : Total analyse 0 targets.
2022-11-02 18:04:28.478  INFO 18504 --- [           main] tabby.core.Analyser                      : Nothing to analysis!
2022-11-02 18:04:28.478  INFO 18504 --- [           main] tabby.core.Analyser                      : Start to save cache.
2022-11-02 18:04:28.478  INFO 18504 --- [           main] tabby.core.container.DataContainer       : Save cache to CSV.
2022-11-02 18:04:31.439  INFO 18504 --- [           main] tabby.core.container.DataContainer       : Save cache to CSV. DONE!
2022-11-02 18:04:31.447  INFO 18504 --- [           main] tabby.core.container.DataContainer       : Total nodes: 213939, relations: 716885
2022-11-02 18:04:31.447  INFO 18504 --- [           main] tabby.core.container.DataContainer       : Clean old tabby.core.data in Neo4j.
```

**Comment by FizzFish** [comment]
跟了一下代码，发现excludeJDK=true时，完全不分析jdk。然而debug时，save2Neo4j函数依然有大量的nodes和relations.
而且进入neo4j后，感觉里面的内容是jdk里的节点信息。
这是什么原因呢？
  @wh1t3p1g 
```
# jdk settings
tabby.build.isJDKProcess              = false
tabby.build.withAllJDK                = false
tabby.build.excludeJDK                = true
tabby.build.isJDKOnly                 = false
```
![runsoot](https://user-images.githubusercontent.com/12733771/199492132-4b951643-a65b-45f8-b54f-c3c19bbe1d69.PNG)
![before_save2neo4j](https://user-images.githubusercontent.com/12733771/199492131-0908b056-a3dd-4fed-ba9c-49955ef27c35.PNG)
![neo4j](https://user-images.githubusercontent.com/12733771/199492130-5e9c2642-079c-488e-8408-cdec451faacd.PNG)

**Comment by FizzFish** [comment]
找到问题了，原来运行是增量的，因此需要先将cache下的内容删除，才会得到本次的运行结果。

**Comment by wh1t3p1g** [comment]
是的 我更新了run.sh，后面运行可以`./run.sh clean`

**Comment by PeanutZhang** [comment]
我的项目中没有caches文件夹?,我自己写了测试包，就几个类，打包分析的时候，还是分析了八百多个类：
待分析的测试源码: 
![image](https://github.com/wh1t3p1g/tabby/assets/24507474/c615e8e0-992c-4efd-b007-319da9b4294e)

配置文件：
# need to modify
#是否开启代码属性图生成
tabby.build.enable                        = true
#?是否开启图导入到 neo4j
tabby.load.enable                         = false

tabby.build.target                        = cases/SimpleJava.jar
# 不需要全量分析的依赖文件目录，加快分析速度
tabby.build.libraries                     = libs

#  分析类型 web 或 gadget，web模式会剔除常见jar包的全量分析，gadget模式会对target目录下的文件进行全量分析
tabby.build.mode                          = web

tabby.output.directory                    = ./output/dev

# debug
tabby.debug.details                       = false

#---------------------------------------------------------------------------------------------------------------------------
# jdk settings
# 分析过程是否加入基础的2个jdk依赖
tabby.build.isJDKProcess                  = false

# 分析过程是否加入全量的jdk依赖
tabby.build.withAllJDK                    = false

# 分析过程是否剔除当前运行环境的jdk依赖，此时target目录需要提供需要分析的jdk依赖
tabby.build.excludeJDK                    = false

# 分析过程是否仅分析jdk依赖，不会去分析target目录下的文件
tabby.build.isJDKOnly                     = false

#-------------------------------------------------------------------------------------------------------------------------

# dealing fatjar
tabby.build.checkFatJar                   = true

# pointed-to analysis
tabby.build.isFullCallGraphCreate         = false
tabby.build.thread.timeout                = 2
tabby.build.isNeedToCreateIgnoreList      = false

输出日志:
2023-08-09 14:31:05.363  INFO 155646 --- [           main] tabby.core.Analyser                      : Total cost 0 min 16 seconds.
2023-08-09 14:31:05.370  INFO 155646 --- [           main] tabby.core.container.DataContainer       : Total 22954, classes: 1975, methods: 20979
2023-08-09 14:31:05.435  INFO 155646 --- [           main] t.d.c.service.RelationshipsService       : Total 44973, has count: 20979, call count: 17449, extend count: 461, alias count: 48

--------------------------
显示了分析了 1975个类，
q:  我的理解是不分析jdk的话，只会分析上边源码中自己写的那5个类？， 是我理解错了吗？ ,有参数配置只分析自己写的类吗？

**Comment by wh1t3p1g** [comment]
因为分析测试类的时候会依赖一些jdk的类，这部分为了更精确的分析，会把依赖到的jdk相关类函数进行分析。所以这里2k左右是正常的，速度上也不会有影响。
而正常带入jdk全量分析大概会在2w多个类的样子。

**Comment by wh1t3p1g** [comment]
`Failed to convert` 这个错误是soot的问题，可能当前函数分析不了，但是其他函数不影响。最终结束还是因为OOM。

**Comment by wh1t3p1g** [comment]
当mode为web的时候，会过滤掉commonJars.json里面符合前缀的jar文件。暂时没有对单个类或包名做过滤的功能。
但是不建议把jdk直接排除掉分析哈

**Comment by PeanutZhang** [comment]
噢噢，我要自己改的话，如何修改源码呢，我是想排除掉android相关的类，数据量太庞大了，我是想分析自己写的代码的调用链，所以第三方和系统的类不太需要

**Comment by wh1t3p1g** [comment]
[filter加在这里](https://github.com/wh1t3p1g/tabby/blob/46be8055c6204c43eefefc7c6982001e52829bf5/src/main/java/tabby/core/scanner/ClassInfoScanner.java#L170)，但是还是不推荐去掉，应该会影响分析的准确性。

**Comment by wh1t3p1g** [comment]
> 谢谢师傅， 那可以把文件拆开成小的去分析, 看了两天源码，我在找如何跳过第三方库模块的方法，比如过滤掉“androidx.xxx." "java.util.xxx","sun.xxx”开头的类或者第三方库，尝试了在ClassInfoScanner#loadAndExtract()方法下过滤掉一些类， ![image](https://user-images.githubusercontent.com/24507474/259697757-b740ffcf-bc7f-48a7-b81c-7126e3636472.png) ![image](https://user-images.githubusercontent.com/24507474/259697961-47c4b502-35ab-4ebf-94b9-29299900969f.png)
> 
> 但是扫描后public_classes.csv中还是有这些类，并没有起到过滤效果，我猜是添加relatClassName时引入了类，同样我在classinfocollector#getAllFatherNodes(cls) 方法中添加过滤逻辑，同样没有起到过滤效果
> 
> 我看之前的历史记录rule下边有exclude.json, 这个文件是按包名或者类吗过滤的吗， 没有找到这个过滤逻辑， 请教下师傅有没有方法过滤掉一些指定类名或者包名的类，不去加载和分析呢

通过当前加的位置去掉后，跟你当前程序无关/不涉及的类都会去掉。但最后递归分析依赖到的一些类最好还是保留下来

**Comment by PeanutZhang** [comment]
> [filter加在这里](https://github.com/wh1t3p1g/tabby/blob/46be8055c6204c43eefefc7c6982001e52829bf5/src/main/java/tabby/core/scanner/ClassInfoScanner.java#L170)，但是还是不推荐去掉，应该会影响分析的准确性。

谢谢师傅，我去研究研究
