### ISSUE TITLE
内存要求有点高，总是报错

### ISSUE THREAD

**Issue by veo** [wh1t3p1g/tabby#39]
mac 16G内存勉强能跑

但远程机器 E5 4线程8G内存

跑了好几天，改动 neo4j 内存配置，改动 java 内存配置，一直没跑完过，各种内存错误
`Exception: java.lang.OutOfMemoryError thrown from the UncaughtExceptionHandler in thread "main"`

作者有没有优化下GC的可能啊，要不然太吃内存了，16G以下机器根本干不动

**Comment by wh1t3p1g** [comment]
程序分析本身就是耗内存的一件事情哈，内存大是必要的。
8g内存跑个2、3w个类还是可以的

**Comment by veo** [comment]
好吧，知道了。我那个5w个类左右，跑不动
