### ISSUE TITLE
在 IDEA 下运行报错，jdk 版本 8u301

### ISSUE THREAD

**Issue by Drun1baby** [wh1t3p1g/tabby#41]
![image](https://user-images.githubusercontent.com/75228348/210938754-b94626b6-32d9-46b1-b8d9-97b70fca2d04.png)

报错信息如图

不太理解是为什么，卡了有一段时间了，还请师傅指点一二

![image](https://user-images.githubusercontent.com/75228348/210938833-84c5e55c-dd22-4483-a7d9-f29df51029ab.png)

**Comment by Drun1baby** [comment]
> neo4j没有配apoc的插件

安装了 apoc 插件之后，报错变成了这个
![image](https://user-images.githubusercontent.com/75228348/210968832-0ea11e66-9614-4663-8ade-b2d82d18b745.png)

**Comment by wh1t3p1g** [comment]
1. 检查一下是否配置完成 https://github.com/wh1t3p1g/tabby/wiki/Neo4j%E7%8E%AF%E5%A2%83%E9%85%8D%E7%BD%AE
2. 保证tabby和neo4j在同一个主机上

**Comment by Drun1baby** [comment]
> 1. 检查一下是否配置完成 https://github.com/wh1t3p1g/tabby/wiki/Neo4j%E7%8E%AF%E5%A2%83%E9%85%8D%E7%BD%AE
> 2. 保证tabby和neo4j在同一个主机上

已检查，配置完成，确保 tabby 和 neo4j 处于同一主机。

![image](https://user-images.githubusercontent.com/75228348/210970446-304bc258-c92f-41cf-968f-08fb1a01af86.png)

**Comment by wh1t3p1g** [comment]
neo4j数据库版本呢
最新的neo4j 5 语法上可能有一些区别

**Comment by Drun1baby** [comment]
> neo4j数据库版本呢 最新的neo4j 5 语法上可能有一些区别

数据库版本和师傅教程里面的是一样的，4.2.1

![image](https://user-images.githubusercontent.com/75228348/210976200-023bbd5b-88a3-42f8-aaff-0c51a9099616.png)

**Comment by wh1t3p1g** [comment]
看具体错误可能导致在 neo4j/repository 的路径调用缺失，你看看动态调一下是哪里出了问题

**Comment by Drun1baby** [comment]
> 看具体错误可能导致在 neo4j/repository 的路径调用缺失，你看看动态调一下是哪里出了问题

看了很久，没有找出对应存在问题的地方

**Comment by Drun1baby** [comment]
值得一提的是，在 neo4j 当中 browser 输入 ":sysinfo" 会得到如下报错

![image](https://user-images.githubusercontent.com/75228348/211253967-892a9da5-1ce2-43d2-ba37-95659c9ad014.png)

**Comment by wh1t3p1g** [comment]
我更新了一下小版本，你可以用最新版的neo4j数据库试一下

**Comment by Drun1baby** [comment]
> 我更新了一下小版本，你可以用最新版的neo4j数据库试一下

师傅好，我又重新尝试了一下，这样子算是 tabby 可以跑起来了嘛

![image](https://user-images.githubusercontent.com/75228348/211857027-ef46f40d-0ff0-4b59-88ea-58710b0bf808.png)

但是查询 tabby 时报错  `CALL tabby.help('all')`

![image](https://user-images.githubusercontent.com/75228348/211856792-6fd5c2c7-e916-405f-8702-569e033665ae.png)

我已经将 tabby 分析插件装在了 plugin 中，并且在 setting 中添加配置如下

```conf
dbms.security.procedures.unrestricted=apoc.*,tabby.*
dbms.security.procedures.allowlist=apoc.*,gds.*,tabby.*
```

![image](https://user-images.githubusercontent.com/75228348/211856948-77f79543-9089-45ed-922a-69e2d7e890c7.png)

![image](https://user-images.githubusercontent.com/75228348/211857887-cedfbc50-9d26-4081-ad55-5ec6d126d61a.png)

**Comment by Drun1baby** [comment]
对应 sysinfo 的报错

![image](https://user-images.githubusercontent.com/75228348/211859052-60f937e1-fbd3-4d3a-b101-2bbbbec95348.png)

使用的 neo4j 版本是 5.2，且插件都是 5.2 的版本

**Comment by wh1t3p1g** [comment]
这样算跑起来了，tabby-path-finder help有点小问题，其他的函数是可以用的

**Comment by Drun1baby** [comment]
> 这样算跑起来了，tabby-path-finder help有点小问题，其他的函数是可以用的

好的多谢师傅，输入 `:sysinfo` 命令这样子报错没关系嘛
