### ISSUE TITLE
tabby-path-finder.jar插件支持函数只有两个findAllPaths和findAllJavaGadget

### ISSUE THREAD

**Issue by songxiaomo1997** [wh1t3p1g/tabby#42]
直接使用env中的tabby-path-finder.jar支持函数只有两个findAllPaths和findAllJavaGadget，使用师傅另外的仓库编译的jar包能用的函数也只有两个

**Comment by wh1t3p1g** [comment]
最新版本仅保留了 2 种函数，可以看一下 readme https://github.com/wh1t3p1g/tabby-path-finder
