### ISSUE TITLE
运行出错

### ISSUE THREAD

**Issue by crisprss** [wh1t3p1g/tabby#55]
Mac下非Docker neo4j启动后，运行tabby出现报错如下
![image](https://github.com/wh1t3p1g/tabby/assets/55953931/1b089aac-b6d9-4165-bf6e-9dcf8caf2774)

开启tabby.cache.isDockerImportPath=False，并且tabby.cache.directory使用了import的绝对路径

**Comment by wh1t3p1g** [comment]
检查一下neo4j是否配置了任意目录读的配置

**Comment by crisprss** [comment]
将neo4j.conf中server.directories.import=import已注释，还是存在下图中情况
![image](https://github.com/wh1t3p1g/tabby/assets/55953931/655ac3e3-19a4-4a28-a95d-e30f55906d26)

**Comment by wh1t3p1g** [comment]
参考一下这个 https://github.com/wh1t3p1g/tabby/blob/master/doc/Neo4j%20%E7%8E%AF%E5%A2%83%E9%85%8D%E7%BD%AE%20%20V5.md
