### ISSUE TITLE
目前tabby分析类关系不支持java源代码输入吗？必须是编译好的jar包？

### ISSUE THREAD

**Issue by zhizhixiongxuwei** [wh1t3p1g/tabby#56]
有些代码如果仅是部分代码不能编译情况下能否使用tabby分析

**Comment by wh1t3p1g** [comment]
soot有处理这部分的逻辑，但是它的源码前端比较老，效果不好。
另外，如果不能编译的原因是代码有问题，应该也处理不了。

**Comment by zhizhixiongxuwei** [comment]
原来如此，我之前处理过一些maven工程代码除了JDK或者常见框架jar包，有些内部pom依赖缺失这时候就很尴尬。
还是谢谢回答

**Comment by wh1t3p1g** [comment]
那确实没什么办法，对于这种情况可以试试用 semgrep

**Comment by zhizhixiongxuwei** [comment]
好的。其实我之前找过一个替代方案eclipse ecj相当于直接走正规流程ast parser，然后后面就得靠自己自定义cfg cg等来构建数据流。不过就是得造轮子。。
