### ISSUE TITLE
毕业论文

### ISSUE THREAD

**Issue by canliture** [wh1t3p1g/tabby#6]
如题，请问文中提到的毕业论文，有没有公开的下载链接。

**Comment by wh1t3p1g** [comment]
当前还没有公开，后续应该能在知网上下到

**Comment by turn1tup** [comment]
打扰，能提供以下论文的标题吗。

**Comment by NatsuGaOwatta** [comment]
目前有关键字可以检索到的吗？顺便问一下师傅是怎么学习使用 soot 的，有文档啥的吗，官方的 wiki 也太难读了😭

**Comment by wh1t3p1g** [comment]
@NatsuGaOwatta 估计快了还没公开。我是边调边学的，目前有些参数也还没配成功过🤦‍♂️，不然就不用自己写指针分析了

**Comment by LioTree** [comment]
请问现在师傅毕业论文公开了吗，求个关键字
