### ISSUE TITLE
如何设置配置文件

### ISSUE THREAD

**Issue by kento996** [wh1t3p1g/tabby#61]
<img width="384" alt="image" src="https://github.com/wh1t3p1g/tabby/assets/72925466/69347e78-497c-47dc-a523-067dc0b59f0c">
请问我想分析一个题目，结构如上，在如下配置文件中应该如何配置呢：
<img width="628" alt="image" src="https://github.com/wh1t3p1g/tabby/assets/72925466/322d487d-e880-48c2-bab1-e04cecaacf4d">

**Comment by wh1t3p1g** [comment]
1. target配置deserbug
2. 如果是分析gadget，libraries可以不改
