### ISSUE TITLE
Tabby分析的Call路径，未能将类的静态方法作为Call路径分析

### ISSUE THREAD

**Issue by alan-he** [wh1t3p1g/tabby#63]
使用Tabby分析jar后，在GRAPHDB_PUBLIC_METHODS.csv中是有类的静态方法的。但实际代码中调用关系未体现在GRAPHDB_PUBLIC_CALL.csv中。

**Comment by wh1t3p1g** [comment]
对于静态方法且没有传参的函数是默认不分析的，所以也就没有call边

**Comment by alan-he** [comment]
> 对于静态方法且没有传参的函数是默认不分析的，所以也就没有call边

有传参的，定义是这样的
class FileUtils {...
public static String doSomethingStatic(ServiceA servA, ServiceB servB, String path, String dstPath, String pkgName)...

调用时这样
FileUtils.doSomethingStatic(servAInst, ServiceB servBInst, path, dstPath, pkgName);

但这个调用没有出现在CAll表格中

**Comment by wh1t3p1g** [comment]
还有一种情况是参数都被分析为不可控的，也会被清掉
