### ISSUE TITLE
可以分析android项目吗

### ISSUE THREAD

**Issue by PeanutZhang** [wh1t3p1g/tabby#64]
请问这个库如何生成android项目的调用链呢

**Comment by PeanutZhang** [comment]
> 目前没有直接处理dex的，可以用一些工具转成jar之后再分析
感谢大佬回复，
意思是把apk文件解压，再把全部dex转成jar吗

**Comment by wh1t3p1g** [comment]
是的哈，但是没有测试过安卓的项目，不确定效果好不好
