### ISSUE TITLE
报错了，请问是啥意思

### ISSUE THREAD

**Issue by xsshim** [wh1t3p1g/tabby#69]
![image](https://github.com/wh1t3p1g/tabby/assets/24834308/a2c6ce76-d912-4b0f-a7dd-c4426a1866fe)

![image](https://github.com/wh1t3p1g/tabby/assets/24834308/a58f407f-4472-4ed1-b589-7d8f1bd949db)

**Comment by wh1t3p1g** [comment]
neo4j没有配置正确，需要加上插件apoc
