### ISSUE TITLE
大佬请问，对目标项目大小和类型有限制吗？

### ISSUE THREAD

**Issue by MountainCui25** [wh1t3p1g/tabby#72]
比如oracle的补丁包，或者codeql无法正常做库的项目

**Comment by wh1t3p1g** [comment]
目前，支持war、jar、class、jsp这些文件的处理，如果输入都是这些文件组成的话，应该都能分析。
另外，还取决于你的硬件，内存多大，CPU核数多少。一般情况，项目越大消耗的越多，时间也会花的更长。推荐搞个服务器来跑。

**Comment by MountainCui25** [comment]
了解，感谢
