### ISSUE TITLE
节点属性问题

### ISSUE THREAD

**Issue by l0n3rs** [wh1t3p1g/tabby#74]
师傅您好，请问有关于Class、Method这两类节点详细的属性说明文档吗？如果有的话方便发一下地址吗，谢谢！

**Comment by wh1t3p1g** [comment]
暂时还没有哈，可以看 neo4j browser 属性的地方，目前应该没有比较特殊的命名。如果有不懂的，可以在这里问。

**Comment by wh1t3p1g** [comment]
增加了一些属性上的介绍，见https://www.yuque.com/wh1t3p1g/tp0c1t/pppuq72tfhmic3g4
