### ISSUE TITLE
运行出错

### ISSUE THREAD

**Issue by wuphao** [wh1t3p1g/tabby#77]
![image](https://github.com/wh1t3p1g/tabby/assets/140902568/dfa06f9c-25bb-4f4d-9db1-4f31d42c79aa)
师傅，能看一下这个报错吗，不明白为啥会报一个settings.properties file not found

**Comment by wh1t3p1g** [comment]
运行前要先配置好settings.properites 
https://github.com/wh1t3p1g/tabby/blob/master/config/settings.properties

**Comment by wuphao** [comment]
![image](https://github.com/wh1t3p1g/tabby/assets/140902568/341db0ad-ba0d-4f74-92b0-db68629c7c64)
settings.properites里面是这样的，还是报错😭

**Comment by wh1t3p1g** [comment]
那看下运行路径，一般是在tabby.jar同级config/settings.properties
