### ISSUE TITLE
数据库没数据❓

### ISSUE THREAD

**Issue by agneitnyreh** [wh1t3p1g/tabby#78]
师傅，1.3版本数据库咋填
![image](https://github.com/wh1t3p1g/tabby/assets/131347347/bc86b21c-1883-40b5-bc2b-c0b7ed9a94ea)
![image](https://github.com/wh1t3p1g/tabby/assets/131347347/25841352-1adb-4016-8181-bcb3d7842117)
![image](https://github.com/wh1t3p1g/tabby/assets/131347347/a1c58462-1148-4ba1-907c-ff8bf1878d50)

**Comment by wh1t3p1g** [comment]
数据库的导入用的 tabby-vul-finder，config/db.properties

**Comment by agneitnyreh** [comment]
🆗，谢谢师傅
