### ISSUE TITLE
CALL tabby.help('all') (no changes, no records)

### ISSUE THREAD

**Issue by yellowhai** [wh1t3p1g/tabby#79]
![1705631070958](https://github.com/wh1t3p1g/tabby/assets/22163713/ca5fb979-d2e8-459d-8d64-da2bc5e28f0f)
<img width="229" alt="image" src="https://github.com/wh1t3p1g/tabby/assets/22163713/23dedd86-0f3f-443b-94d8-43451f77ad5d">

**Comment by wh1t3p1g** [comment]
这个是正常的，改用 `tabby.help("tabby")` 来确认是否安装成功

**Comment by yellowhai** [comment]
<img width="891" alt="image" src="https://github.com/wh1t3p1g/tabby/assets/22163713/41d86f62-9e9a-41ba-8d3e-bb050942f363">
大哥我说怎么半天没用！！！
