### ISSUE TITLE
与codeql的区别？

### ISSUE THREAD

**Issue by HomerQing** [wh1t3p1g/tabby#8]
初一看感觉与codeql功能比较类似，请问下作者tabby与codeql相比有哪些功能上的区别或优势？

**Comment by wh1t3p1g** [comment]
你好，
你可以简单认为是同一类的工具
tabby更多面向的是已编译的JAR/CLASS/WAR。对于，我们研究商业化软件的漏洞有一定的帮助，比如类似weblogic这种。tabby起到辅助漏洞挖掘的作用是当前的预期，不管是辅助理解当前jar的代码继承关系之类的信息，还是直接查找特定漏洞链路。
codeql以我个人的理解面向的更多是源码级别的（java方面），它当前还是不能直接去分析类似jar这种文件的

**Comment by HomerQing** [comment]
了解了，谢谢回复！
