### ISSUE TITLE
大佬，什么时候开源2.0啊，好像看看大佬的新版本的实现到底是什么思路。

### ISSUE THREAD

**Issue by ewqdsadwqe** [wh1t3p1g/tabby#82]

**Comment by ewqdsadwqe** [comment]
可能有点太过冲动了，如果不方便开源的话，能不能给出一些 2.0 版本对比当前版本的优化思路提示啊？ 因为我自己也在学习和尝试开发自动化代码审计工具，目前是基于 GI 做的修改，但是感觉 GI 的静态分析调用图部分满足不了多态分析和无效控制流分析之类的需要了，所以开始参考 tabby 和 tai-e ，逐步的学习大佬的思路和补基础知识之类的，所以看不到 2.0有点着急，想问下是2.0 对于 1.2 ，在什么方面做了改进啊？如果能给出一些具体的例子 和 思路那就更好了，感激不尽。

**Comment by wh1t3p1g** [comment]
开源版本是最早写的一版，如果你看过代码的话，会发现污点分析这块其实并不是太符合worklist算法那套东西的。还有语义缓存的实现也不是很完备。最终，在结果上，你可以看到误报会很多。
所以当时决定不再维护开源版本的污点分析这块的代码。后续重新理了理思路，做了代码上的重构。实现过程中的一些细节、概念可以参考kcon 2022上的分享。不过，这个分享距今也有一段时间了，有了些其他的改进，这个后续有时间再分享下。
至于，开源时间这个暂时还没办法确定。

**Comment by ewqdsadwqe** [comment]
谢谢，期待后续的分享，我继续学习了。
