### ISSUE TITLE
生成的图缺少某个方法调用的关系

### ISSUE THREAD

**Issue by justdoit-cai** [wh1t3p1g/tabby#89]
我在分析jooq-3.19.3.jar的时候，明明org.jooq.impl.Convert$ConvertAll.from()方法中调用了newInstance()方法，但是Tabby没查出来。
![image](https://github.com/wh1t3p1g/tabby/assets/126458073/ed9ce769-43a5-4abb-8b69-e01112dda112)
![image](https://github.com/wh1t3p1g/tabby/assets/126458073/7724dc88-b3c7-4be9-9bbb-94b768b219b9)

**Comment by wh1t3p1g** [comment]
如果不敏感的话，可以提供一下jar，我找时间看一下

**Comment by justdoit-cai** [comment]
<dependency>
            <groupId>org.jooq</groupId>
            <artifactId>jooq</artifactId>
            <version>3.19.3</version>
        </dependency>

**Comment by wh1t3p1g** [comment]
删除了非污点函数调用的过滤；
另外，因为污点分析不准确，在call边上的污点会被丢失，可以在system.json里添加对应的规则，例如下面这个例子
```json
  {"name": "org.jooq.impl.Convert", "rules": [
    {"function": "convert", "type": "know", "vul": "", "actions": {"return": "param-0"}, "polluted": [], "signatures": []}
  ]},
```
