### ISSUE TITLE
关于tabby调用图构建的入口问题

### ISSUE THREAD

**Issue by Spr1n9T1me** [wh1t3p1g/tabby#90]
请问tabby1.3构建调用图时，对于第三方库而言入口方法是如何处理的呢，还有能否自定义入口？

**Comment by wh1t3p1g** [comment]
tabby是全量函数调用图构建，包括三方库。
如果mode选择了gadget，会对目标里的所有可识别文件做调用图构建
如果mode选择了web，会过滤掉commonJars.json里面的jar，其他的可识别文件进行调用图构建

**Comment by Spr1n9T1me** [comment]
感谢解惑
