### ISSUE TITLE
如何在tabby解析的结果中获取到函数对应的源代码？

### ISSUE THREAD

**Issue by Wangkxkx** [wh1t3p1g/tabby#93]

**Comment by Wangkxkx** [comment]
大佬，请教一下，我现在用tabby过滤出了我想要审计的函数，请问我可以直接使用taaby获取到函数的源代码吗？如果不能，有没有什么其他解决方案呢？

**Comment by wh1t3p1g** [comment]
我习惯用IDEA，复制NAME0的值，双击shift就可以定位到了。另外，也可以用下我改的IDEA插件

**Comment by Wangkxkx** [comment]
是的！我看到了您开发的插件，很好用。不过现阶段希望批量将源代码导出，请问有什么办法吗？

**Comment by wh1t3p1g** [comment]
目前没办法从代码属性图到源码哈，你可以尝试用parser解析反编译后的文件后再跟代码属性图做关联

**Comment by Wangkxkx** [comment]
嗯呢好的，感谢回答！
