### ISSUE TITLE
生成的GRAPHDB_PUBLIC_METHODS.csv，一些属性如IS_SERIALIZABLE获取不正确

### ISSUE THREAD

**Issue by R1ckyZ** [wh1t3p1g/tabby#96]
之前使用的时候都是准确的，主要是我最近下了新版出现的这个问题，我不太确定是tabby.jar本身问题还是我配置文件的问题，我设置的有关jdk的选项如下
```
tabby.build.useSettingJRE                 = false
tabby.build.isJRE9Module                  = true
tabby.build.javaHome                      = /opt/jdk1.8.0_202
tabby.build.isJDKProcess                  = true
tabby.build.withAllJDK                    = false
tabby.build.isJDKOnly                     = false
```
生成的GRAPHDB_PUBLIC_METHODS.csv中IS_SERIALIZABLE全为false，例如java.util.HashMap下面的IS_SERIALIZABLE也都为false
![image](https://github.com/user-attachments/assets/f70a8302-5090-4387-926d-ac3371a05e99)
如果新版的tabby.jar本身不存在此问题的话，我想问一下是不是我配置文件设置的问题？

**Comment by wh1t3p1g** [comment]
是最新打包的jar吗，release里面可能不是最新的

**Comment by R1ckyZ** [comment]
> 是最新打包的jar吗，release里面可能不是最新的

谢谢，是release里面提供的tabby.jar存在问题，需要自己重新编译一个tabby.jar。
